controllers/AdminFaqController.php
<?php

namespace app\controllers;

use Yii;
use app\components\AdminController;
use yii\web\NotFoundHttpException;
use app\models\Faq;
use yii\data\ActiveDataProvider;

class AdminFaqController extends AdminController {

    public function actionIndex()
    {
        $query = Faq::find();

        $dataProvider = new ActiveDataProvider([
            'query' => $query,
            'sort' => [
                'defaultOrder'=>['id'=>SORT_DESC]
            ]
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionCreate()
    {
        $model = new Faq();

        if ($model->load(Yii::$app->request->post())) {
            if ($model->validate()) {
                $model->save();
                return $this->redirect(['index']);
            }
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post())) {
            if ($model->validate()) {
                $model->save();
                return $this->redirect(['index']);
            }
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    public function actionDelete($id)
    {
        try {
            $this->findModel($id)->delete();
        } catch (\yii\base\Exception $e) {
            return $this->pjaxRefreshAlert(Yii::t('app',"Can't delete this item, it is use by another item(s)"));
        }
        return $this->pjaxRefresh();
    }

    protected function findModel($id)
    {
        if (($model = Faq::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

}

views/admin-faq/_form.php
<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

?>

<div class="admin-form">

    <?php $form = ActiveForm::begin(['layout' => 'horizontal']); ?>
	
	<div class="row">
        <div class="col-sm-6 col-sm-offset-3">
            <ul class="nav nav-tabs" role="tablist">
                <li class="active"><a href="#tab1" role="tab" data-toggle="tab"><?=Yii::t('app','DE')?></a></li>
                <li><a href="#tab2" role="tab" data-toggle="tab"><?=Yii::t('app','EN')?></a></li>
                <li><a href="#tab3" role="tab" data-toggle="tab"><?=Yii::t('app','RU')?></a></li>
            </ul>
        </div>
    </div>
	<br>
	
	<div class="tab-content">
        <div role="tabpanel" class="tab-pane active" id="tab1">
          <?= $form->field($model, 'question_de')->textInput(['maxlength' => 256]) ?>
          <?= $form->field($model, 'response_de')->textarea(['rows' => 10]) ?>
        </div>
        <div role="tabpanel" class="tab-pane" id="tab2">
            <?= $form->field($model, 'question_en')->textInput(['maxlength' => 256]) ?>
            <?= $form->field($model, 'response_en')->textarea(['rows' => 10]) ?>
        </div>
        <div role="tabpanel" class="tab-pane" id="tab3">
            <?= $form->field($model, 'question_ru')->textInput(['maxlength' => 256]) ?>
			<?= $form->field($model, 'response_ru')->textarea(['rows' => 10]) ?>
        </div>
    </div>

   

    <div class="form-group">
        <div class="col-sm-6 col-sm-offset-3">
            <?= Html::submitButton($model->isNewRecord ? Yii::t('app', 'Create') : Yii::t('app', 'Save'), ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
            <?= Html::button(Yii::t('app', 'Cancel'), ['class' => 'btn btn-default','style'=>'margin-left:10px;','onclick'=>'history.back();']) ?>
        </div>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/admin-faq/create.php
<?php

use yii\helpers\Html;

$this->title=Yii::t('app', 'Creating question');

$this->params['breadcrumbs']=[
    [
        'label'=>Yii::t('app','Fragen / Antworten'),
        'url'=>['admin-faq/index']
    ],
    [
        'label'=>$this->title,
    ]
];

?>

<div class="admin-create">
    <h1><?php echo Html::encode($this->title); ?></h1>
    <?= $this->render('_form', ['model' => $model]); ?>
</div>

views/admin-faq/index.php
<?php

use yii\helpers\Html;
use app\components\GridView;

$this->params['breadcrumbs']=[
    [
        'label'=>Yii::t('app','Fragen / Antworten'),
        'url'=>['admin-faq/index']
    ]
];

?>

<div class="admin-index">

    <h1>
        <?= Html::a(Yii::t('app', 'Create'), ['create'], ['class' => 'btn btn-success pull-right']) ?>

        <?= Html::encode(Yii::t('app','Fragen / Antworten')) ?>
    </h1>

    <p>
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'columns' => [
            [
                'attribute'=>'question_de',
                'value'=>'question_de',
                'options'=>['style'=>'width: 250px;']
            ],
            [
                'attribute'=>'response_de',
                'value'=>'response_de',
                'contentOptions'=> [
                    'class'=>'description'
                ]
            ],
            [
                'class' => 'app\components\ActionColumn',
                'template' => '{update} {delete}'
            ],
        ],
    ]); ?>

</div>

views/admin-faq/update.php
<?php

use yii\helpers\Html;

$this->title=Yii::t('app','Updating question');

$this->params['breadcrumbs']=[
    [
        'label'=>Yii::t('app','Fragen / Antworten'),
        'url'=>['admin-faq/index']
    ],
    [
        'label'=>$this->title,
    ]
];

?>

<div class="admin-update">
    <h1><?php echo Html::encode($this->title); ?></h1>
    <?= $this->render('_form', ['model' => $model]); ?>
</div>