controllers/AdminInfoController.php
<?php

namespace app\controllers;

use Yii;
use app\components\AdminController;
use app\models\Info;
use yii\web\NotFoundHttpException;
use app\models\InfoSearch;


class AdminInfoController extends AdminController {

    public function actionIndex() {
        $searchModel = new InfoSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionUpdate($id) {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post())) {
            if ($model->validate()) {
                $model->save();
                return $this->redirect(['index']);
            }
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    protected function findModel($id) {
        if (($model = Info::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }


}

views/admin-info/_form.php
<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use app\components\Ckeditor;

?>

<div class="admin-form">

    <?php $form = ActiveForm::begin(['layout' => 'horizontal']); ?>

    <div class="row">
        <div class="col-sm-6 col-sm-offset-3">
            <ul class="nav nav-tabs" role="tablist">
                <li class="active"><a href="#tab1" role="tab" data-toggle="tab"><?=Yii::t('app','DE')?></a></li>
                <li><a href="#tab2" role="tab" data-toggle="tab"><?=Yii::t('app','EN')?></a></li>
                <li><a href="#tab3" role="tab" data-toggle="tab"><?=Yii::t('app','RU')?></a></li>
            </ul>
        </div>
    </div>

    <br>
    <div class="tab-content">
        <div role="tabpanel" class="tab-pane active" id="tab1">
            <?= $form->field($model, 'title_de')->textInput(['maxlength' => 256]) ?>
            <?= $form->field($model, 'description_de')->widget(Ckeditor::className(), [
                'clientOptions'=>[
                    'height'=>'400'
                ]
            ]) ?>
        </div>
        <div role="tabpanel" class="tab-pane" id="tab2">
            <?= $form->field($model, 'title_en')->textInput(['maxlength' => 256]) ?>
            <?= $form->field($model, 'description_en')->widget(Ckeditor::className(), [
                'clientOptions'=>[
                    'height'=>'400'
                ]
            ]) ?>
        </div>
        <div role="tabpanel" class="tab-pane" id="tab3">
            <?= $form->field($model, 'title_ru')->textInput(['maxlength' => 256]) ?>
            <?= $form->field($model, 'description_ru')->widget(Ckeditor::className(), [
                'clientOptions'=>[
                    'height'=>'400'
                ]
            ]) ?>
        </div>
    </div>

    <div class="form-group">
        <div class="col-sm-6 col-sm-offset-3">
            <?= Html::submitButton($model->isNewRecord ? Yii::t('app', 'Create') : Yii::t('app', 'Save'), ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
            <?= Html::button(Yii::t('app', 'Cancel'), ['class' => 'btn btn-default','style'=>'margin-left:10px;','onclick'=>'history.back();']) ?>
        </div>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/admin-info/create.php
<?php

use yii\helpers\Html;

$this->title=Yii::t('app','Creating');

$this->params['breadcrumbs']=[
    [
        'label'=>Yii::t('app','i-Informationen'),
        'url'=>['admin-info/index']
    ],
    [
        'label'=>$this->title,
    ]
];

?>

<div class="admin-create">
    <h1><?php echo Html::encode($this->title); ?></h1>
    <?= $this->render('_form', ['model' => $model]); ?>
</div>

views/admin-info/index.php
<?php

use yii\helpers\Html;
use app\components\GridView;

$this->params['breadcrumbs']=[
    [
        'label'=>Yii::t('app','i-Informationen'),
        'url'=>['admin-info/index']
    ]
];

?>

<div class="admin-index">

    <h1>
        <?= Html::encode(Yii::t('app','i-Informationen')) ?>
    </h1>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            'title_de',
            'view',
            [
                'class' => 'app\components\ActionColumn',
                'template' => '{update} {commetns}',
                'buttons'=> [
                    'commetns' => function($url, $model, $key) {
                        $params = [
                            'title' => Yii::t('app', 'Kommentare'),
                            'class'=>'action-btn',
                            'data-pjax'=>0
                        ];
                        $url = \yii\helpers\Url::to(['/admin-info-comment/list', 'id'=>$model->id]);
                        return Html::a('<span class="glyphicon glyphicon-comment"></span>', $url, $params);

                    }
                ]
            ],

        ],
    ]); ?>

</div>

views/admin-info/update.php
<?php

use yii\helpers\Html;

$this->title=Yii::t('app','Updating');

$this->params['breadcrumbs']=[
    [
        'label'=>Yii::t('app','i-Informationen'),
        'url'=>['admin-info/index']
    ],
    [
        'label'=>$this->title,
    ]
];

?>

<div class="admin-update">
    <h1><?php echo Html::encode($this->title); ?></h1>
    <?= $this->render('_form', ['model' => $model]); ?>
</div>